name: Bug Report
description: Report a bug in the software.
labels: ["Type: Bug Report", "NEW ISSUE"] 
body:
- type: markdown
  attributes:
    value: |
      ## Is there an existing issue for this?
      Please check to see if an issue already exists for the bug you encountered before creating a new issue.
- type: dropdown
  attributes:
    label: Version
    description: What version are you running?
    multiple: false
    options:
      - Lastest
      - Self-Compiled (please specify branch)
      - Other (please specify elsewhere)
  validations:
    required: true
- type: dropdown
  attributes:
    label: OS
    description: What OS are you on?
    multiple: false
    options:
      - Windows
      - Mac
      - Linux (please specify the name)
      - Other
  validations:
    required: true     
- type: textarea
  attributes:
    label: Description
    id: description
    description: |
      Describe your issue(s) / bug(s) here.
- type: textarea
  attributes:
    label: Logs
    description: |
      Please attach any log file(s) and/or console logs here.
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe the steps to reproduce this issue
    placeholder: |
      1. [First Step]
      2. [Second Step]
      3. [And so on...]
- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      What should be happening? If you don't know, leave what you think should happen
- type: textarea
  attributes:
    label: Actual Behavior
    description: |
      What is actually happening?
- type: textarea
  attributes:
    label: Reproduction frequency
    description: |
      How often are you reliably able to reproduce this issue?
- type: textarea
  attributes:
    label: Additional Information
    description: |
       Any additional information, configuration, or data that might be necessary to reproduce the bugs.